#!/bin/bash

if javac -cp .:junit-4.13.2.jar:hamcrest-core-1.3.jar UnitTests.java; then
echo "Compilation Successfull!"
java -cp .:junit-4.13.2.jar:hamcrest-core-1.3.jar org.junit.runner.JUnitCore UnitTests
else
echo "Compilation Failed!"
fi
